---
#done
  - name: Update all packages to the latest version
    sudo: yes
    apt:
      upgrade: dist

  - name: Install the package "foo"
    sudo: yes
    apt:
      name: nginx
      state: present

  - name: copy nginx.conf
    sudo: yes
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root
    # tags:
    #   - nginx

  - name: setup nginx host file dirs
    sudo: yes
    file: name=/etc/nginx/sites-available state=directory owner=root group=root

  - name: setup nginx host file dirs
    sudo: yes
    file: name=/etc/nginx/sites-enabled state=directory owner=root group=root

  - name: ensure default nginx has been deleted
    sudo: yes
    file: dest=/etc/nginx/sites-enabled/default state=absent

  - name: restart nginx
    sudo: yes
    service: name=nginx state=restarted enabled=yes
    # tags:
    #   - nginx