---
#done
  - name: Update all packages to the latest version
    sudo: yes
    apt:
      upgrade: dist

  - name: Install the package "foo"
    sudo: yes
    apt:
      name: nodejs
      state: present

  - name: Install the package "foo"
    sudo: yes
    apt:
      name: npm
      state: present